import type { ComponentType } from "react";

export const React: typeof import("react");
export const FluxDispatcher: any;
export const FluxStore: any;

export const UserStore: any;
export const RelationshipStore: any;
export const GuildStore: any;
export const ChannelStore: any;
export const SelectedChannelStore: any;
export const MediaEngineStore: any;
export const VoiceStateStore: any;
export const PresenceStore: any;
export const MessageStore: any;
export const SelectedGuildStore: any;
export const PermissionStore: any;
export const UserGuildSettingsStore: any;
export const UserProfileStore: any;
export const DraftStore: any;
export const ReadStateStore: any;
export const GuildMemberStore: any;
export const GuildChannelStore: any;
export const InviteStore: any;
export const FriendStore: any;
export const EmojiStore: any;
export const LocaleStore: any;
export const ApplicationStreamingStore: any;
export const RunningGameStore: any;
export const AudioSettingsStore: any;
export const NotificationSettingsStore: any;
export const GuildReadStateStore: any;
export const InviteActions: any;
export const VoiceActions: any;
export const SettingsRouter: any;
export const Menu: any;
export const SpellCheckStore: any;
export const UserSettingsProtoStore: any;
export const ChannelRTCStore: any;
export const ApplicationAssetUtils: any;
export const StreamerModeStore: any;
export const Toasts: any;
export const UserUtils: any;

export function useState<T>(initial: T): [T, (v: T) => void];
export function useEffect(fn: () => void | (() => void), deps?: any[]): void;
export function useReducer<T, A>(reducer: (state: T, action: A) => T, initial: T): [T, (action: A) => void];
export function useStateFromStores<T>(stores: any[], fn: () => T, deps?: any[]): T;
export function useMemo<T>(fn: () => T, deps?: any[]): T;
export function useCallback<T extends Function>(fn: T, deps?: any[]): T;
export function useRef<T>(initial: T): { current: T };
export function useContext<T>(ctx: any): T;
export function createContext<T>(defaultValue: T): any;
export function fetchApplicationsRPC(...args: any[]): Promise<any>;
export function showToast(content: any, props?: any): void;

export const Select: ComponentType<any>;
export const TextInput: ComponentType<any>;
export const TextArea: ComponentType<any>;
export const Slider: ComponentType<any>;
export const Popout: ComponentType<any>;
export const Tooltip: ComponentType<any>;
export const Avatar: ComponentType<any>;
export const Button: ComponentType<any>;
export const Switch: ComponentType<any>;
export const Checkbox: ComponentType<any>;
export const RadioGroup: ComponentType<any>;
export const Dialog: ComponentType<any>;
export const FocusLock: ComponentType<any>;
export const MaskedLink: ComponentType<any>;
export const Timestamp: ComponentType<any>;
export const ScrollerThin: ComponentType<any>;
export const ScrollerAuto: ComponentType<any>;
export const ListScrollerThin: ComponentType<any>;
export const Card: ComponentType<any>;
export const Clickable: ComponentType<any>;
export const Text: ComponentType<any>;
export const Heading: ComponentType<any>;
export const TabBar: ComponentType<any>;
export const Notice: ComponentType<any>;
export const Flex: ComponentType<any>;
