name: autofix.ci

on:
    pull_request:

permissions:
    contents: read

jobs:
    autofix:
        name: autofix
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7

            - uses: pnpm/action-setup@v6

            - name: Use Node.js 24
              uses: actions/setup-node@v7
              with:
                  node-version: 24
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run lint fix
              run: pnpm lint:fix

            - name: Run stylelint fix
              run: pnpm lint-styles:fix

            - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
